### ISSUE TITLE
Streams don't appear in Studio Mode Preview

### ISSUE THREAD

**Issue by gmjosack** [dd-center/obs-streamlink#28]
When using Studio Mode, streams only appear in the Preview pane if they're already loaded in the Program pane. This makes it very difficult to stage a scene before broadcasting it especially because when restarting OBS it often loses the definitions and defaults to displaying the stream at full size.

Is there anyways to force the plugin to load the streams in the Preview pane when using Studio Mode? This would allow users to verify the layout looks good before switching scenes and also pre-load the streams so they're not blank when the scene is first loaded.

**Comment by cqjjjzr** [comment]
I'll check if OBS has an API for that.

**Comment by cqjjjzr** [comment]
Well, it's embarrassing that: OBS only have source toolbar support for their built-in sources, i.e. no support for custom source toolbar, so I can't place a "Stop" and a "Restart Stream" button on the source toolbar.

This means if I use `show` and `hide` functions instead of `activate`/`deactivate`, it would be more cumbersome to pause and restart the stream (currently done by toggling stream visibility). I will look into a better solution...

**Comment by cqjjjzr** [comment]
Try this: https://github.com/dd-center/obs-streamlink/releases/tag/0.3.1

**Comment by gmjosack** [comment]
Just tested and it works great! Thanks so much for the quick turn around!
